name: build-and-publish--biconomy-and-stackup

on:
  push:
    branches: ['main']
  # we can also trigger manually in case needed
  workflow_dispatch:
  pull_request:
    branches: ['main']
    types:
      [closed]
jobs:
  build:
    runs-on: mpc-account-abstraction-sdk-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pushd packages/biconomy && npm i && NEXT_PUBLIC_BASE_URL=https://us-central1-mobile-wallet-mm-snap.cloudfunctions.net npm run build
          popd 
          pushd packages/stackup && npm i && NEXT_PUBLIC_BASE_URL=https://us-central1-mobile-wallet-mm-snap.cloudfunctions.net npm run build
          popd

      - name: Build artifact
        run: |
          /usr/bin/7z a ./biconomy-stackup.7z ./packages/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: biconomy-stackup
          path: ./biconomy-stackup.7z
          
  deploy-staging:
    runs-on: mpc-account-abstraction-sdk-stage-deployer-prod
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: biconomy-stackup
          path: ./
      - run: |
            if [ -d "/opt/service/update" ]; then rm -Rf /opt/service/update; fi 
            mkdir /opt/service/update/
            mv ./biconomy-stackup.7z /opt/service/update/
      - run: cd /opt/service/update/ && 7z x biconomy-stackup.7z
      - run: cd /opt/service/update/biconomy && npm i 
      - run: cd /opt/service/update/stackup && npm i 
      - run: if [ -d "/opt/service/biconomy" ]; then rm -Rf /opt/service/biconomy; fi
      - run: if [ -d "/opt/service/stackup" ]; then rm -Rf /opt/service/stackup; fi
      - run: sudo systemctl restart biconomy.service stackup.service

          
