name: ko-publish-aggregator-and-operator

on:
  push:
    branches: ['CI/CD']
  # we can also trigger manually in case needed
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: mpc-account-abstraction-sdk-deployer
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: | 
            pushd packages/biconomy && npm i
            popd && pushd packages/stackup && npm i 