name: ko-publish-aggregator-and-operator

on:
  push:
    branches: ['main']
  # we can also trigger manually in case needed
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: mpc-account-abstraction-sdk-deployer
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: | 

            if [ -d "/opt/service/biconomy" ]; then rm -Rf /opt/service/biconomy; fi
            if [ -d "/opt/service/stackup" ]; then rm -Rf /opt/service/stackup; fi
            rsync -ac packages/ /opt/service/
            pushd /opt/service/biconomy && npm i
            popd 
            pushd /opt/service/stackup && npm i 
            popd
            sudo systemctl restart biconomy.service stackup.service
